# Generated by Django 5.0.3 on 2024-04-01 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boja', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imeMarke', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VelicinaObuce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velicina', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VelicinaOdece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velicina', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Obuca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('cena', models.PositiveIntegerField()),
                ('stanje', models.CharField(max_length=50)),
                ('opis', models.TextField()),
                ('boja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boja')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.marka')),
            ],
        ),
        migrations.CreateModel(
            name='Odeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('tip', models.CharField(max_length=100)),
                ('cena', models.PositiveIntegerField()),
                ('stanje', models.CharField(max_length=50)),
                ('opis', models.TextField()),
                ('boja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boja')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.marka')),
            ],
        ),
        migrations.CreateModel(
            name='SlikaObuce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='obuca_slike')),
                ('obuca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slike_obuce', to='main.obuca')),
            ],
        ),
        migrations.AddField(
            model_name='obuca',
            name='slike',
            field=models.ManyToManyField(related_name='obuce', to='main.slikaobuce'),
        ),
        migrations.CreateModel(
            name='SlikaOdece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='odeca_slike')),
                ('odeca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slike_odece', to='main.odeca')),
            ],
        ),
        migrations.AddField(
            model_name='odeca',
            name='slike',
            field=models.ManyToManyField(related_name='odece', to='main.slikaodece'),
        ),
        migrations.AddField(
            model_name='obuca',
            name='velicina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.velicinaobuce'),
        ),
        migrations.AddField(
            model_name='odeca',
            name='velicina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.velicinaodece'),
        ),
    ]
