# Generated by Django 5.0.3 on 2024-04-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obuca',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obuca',
            name='stanje',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slikaobuce',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='obuca_slike'),
        ),
        migrations.AlterField(
            model_name='slikaodece',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='odeca_slike'),
        ),
    ]
