# Generated by Django 5.0.3 on 2024-04-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_obuca_opis_alter_obuca_stanje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obuca',
            name='glavnaSlika',
            field=models.ImageField(blank=True, null=True, upload_to='obuca_slike'),
        ),
    ]
