# Generated by Django 5.0.3 on 2024-04-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_obuca_glavnaslika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obuca',
            name='slike',
            field=models.ManyToManyField(blank=True, null=True, related_name='obuce', to='main.slikaobuce'),
        ),
    ]
