# Generated by Django 5.0.3 on 2024-04-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_obuca_slike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='velicinaodece',
            name='velicina',
            field=models.CharField(max_length=20),
        ),
    ]
