# Generated by Django 5.0.3 on 2024-04-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_velicinaodece_velicina'),
    ]

    operations = [
        migrations.AddField(
            model_name='obuca',
            name='sifra',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='odeca',
            name='sifra',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='velicinaobuce',
            name='velicina',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='velicinaodece',
            name='velicina',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
