# Generated by Django 5.0.3 on 2024-04-04 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_odeca_velicina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obuca',
            name='slike',
        ),
        migrations.RemoveField(
            model_name='odeca',
            name='slike',
        ),
        migrations.AlterField(
            model_name='odeca',
            name='velicina',
            field=models.ManyToManyField(to='main.velicinaodece'),
        ),
        migrations.AlterField(
            model_name='slikaobuce',
            name='obuca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slika_obuce', to='main.obuca'),
        ),
        migrations.AlterField(
            model_name='slikaodece',
            name='odeca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slika_odece', to='main.odeca'),
        ),
    ]
