# Generated by Django 5.0.3 on 2024-04-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_obuca_slike_remove_odeca_slike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slikaobuce',
            name='obuca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slike_obuce', to='main.obuca'),
        ),
    ]
