# Generated by Django 5.0.3 on 2024-04-04 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_slikaobuce_obuca'),
    ]

    operations = [
        migrations.AddField(
            model_name='obuca',
            name='slike',
            field=models.ManyToManyField(blank=True, null=True, related_name='obuce', to='main.slikaobuce'),
        ),
        migrations.AddField(
            model_name='odeca',
            name='slike',
            field=models.ManyToManyField(related_name='odece', to='main.slikaodece'),
        ),
        migrations.AlterField(
            model_name='slikaodece',
            name='odeca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slike_odece', to='main.odeca'),
        ),
    ]
