# Generated by Django 5.0.3 on 2024-04-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_nacinkupovine_naziv_alter_nacinkupovine_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='odeca',
            name='glavnaSlika',
            field=models.ImageField(blank=True, null=True, upload_to='odeca_slike'),
        ),
        migrations.AlterField(
            model_name='odeca',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tip'),
        ),
    ]
