# Generated by Django 5.0.3 on 2024-04-13 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_tip_odeca_glavnaslika_alter_odeca_tip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Praćenje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prati', models.BooleanField(default=False)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('obuca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.obuca')),
                ('odeca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.odeca')),
            ],
        ),
    ]
